### ISSUE TITLE
No form input validation

### ISSUE THREAD

**Issue by digidub** [briatulloch/library#1]
Currently there is no input validation on the Add Book form. It's therefore possible to submit books without filling out any of the form fields. It's also possible to enter letters in the "pages" field.

**Comment by briatulloch** [comment]
> Currently there is no input validation on the Add Book form. It's therefore possible to submit books without filling out any of the form fields. It's also possible to enter letters in the "pages" field.

Thank you! I've now added input validation and made it so that only numbers can be added to the 'pages field'.
